version: '3.4'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    container_name: judge0-dev-nginx-proxy
    environment:
      - DEFAULT_HOST=api.judge0.local
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "8080:80"
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - DEV_USER=${USER:-judge0}
        - DEV_USER_ID=${UID:-1000}
    image: judge0/api:dev
    container_name: judge0-dev-api
    environment:
      - VIRTUAL_HOST=api.judge0.local
      - VIRTUAL_PORT=3000
    volumes:
      - .:/usr/src/api
    ports:
      - "3000:3000"
      - "3030:3030"
    privileged: true

  resque-web:
    image: ennexa/resque-web:latest
    container_name: judge0-dev-resque-web
    command: -r redis://redis:6379
    ports:
      - "5678:5678"
    restart: always

  db:
    image: postgres:10.3
    env_file: judge0-api.conf
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:3.2.11
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres-data:
  redis-data: