version: '2'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - DEV_USER=$USER
        - DEV_USER_ID=$UID
    image: judge0/api:dev
    volumes:
      - .:/usr/src/api
    env_file: judge0-api.conf
    ports:
      - "3000:3000"
      - "3030:3030"
    privileged: true

  db:
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/postgresql-data:/var/lib/postgresql/data/
    image: postgres

  redis:
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - ./tmp/redis-data:/data
    image: redis
