version: '2'
services:
  api:
    image: judge0/api:0.1.1
    env_file: judge0-api.conf
    links:
      - db
      - redis
    ports:
      - 3000:3000
    restart: always

  worker:
    image: judge0/api:0.1.1
    env_file: judge0-api.conf
    command: rails resque:work QUEUE=* COUNT=2
    privileged: true
    links:
      - db
      - redis
    restart: always

  db:
    image: postgres
    env_file: judge0-api.conf
    volumes:
      - ./srv/data:/var/lib/postgresql/data/
    restart: always

  redis:
    image: redis
    restart: always
