version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=api.judge0.local
    ports:
      - "8080:80"

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - DEV_USER=$USER
        - DEV_USER_ID=$UID
    image: judge0/api:dev
    volumes:
      - .:/usr/src/api
    environment:
      - VIRTUAL_HOST=api.judge0.local
      - VIRTUAL_PORT=3000
    env_file: judge0-api.conf
    ports:
      - "3000:3000"
      - "3030:3030"
    privileged: true

  resque-web:
    image: ennexa/resque-web
    command: -r redis://redis:6379
    ports:
      - "5678:5678"
    restart: always

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/postgres-data:/var/lib/postgresql/data/

  redis:
    image: redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - ./tmp/redis-data:/data
