default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  host: <%= ENV['POSTGRES_HOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Judge0API_development

test:
  <<: *default
  database: Judge0API_test

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
