version: '2'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        DEV_USER: herman
        DEV_USER_ID: 1000
    image: hermanzdosilovic/judge0-dev
    volumes:
      - .:/usr/src/api
    env_file: judge0-api.env
    ports:
      - 3000:3000
    privileged: true
