version: '2'
services:
  api:
    env_file: judge0-api.env
    ports:
      - 3000:3000

  worker:
    build: .
    image: hermanzdosilovic/judge0-api
    env_file: judge0-api.env
    command: rails resque:work QUEUE=*
    privileged: true
    links:
      - pg
      - redis

  pg:
    volumes:
      - /var/lib/judge0/data:/var/lib/postgresql/data/
