version: '2'
services:
  api:
    build: .
    image: hermanzdosilovic/judge0
    depends_on:
      - pg
      - redis
    links:
      - pg
      - redis
    privileged: true

  pg:
    image: postgres

  redis:
    image: redis
