version: '2'
services:
  api:
    build: .
    image: hermanzdosilovic/judge0
    depends_on:
      - pg
    links:
      - pg
    env_file: .env

  pg:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
